# Generated by Django 5.1 on 2024-08-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='q1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='q2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='q3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='q4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='q5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
