# Generated by Django 5.1 on 2024-08-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_scores_q1_scores_q2_scores_q3_scores_q4_scores_q5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
